---

#
# Builds supporting RDSSARK images used for QA and publishes them to the given
# Docker registry.
#
# Usage:
#
#     $ ansible-playbook publish-qa-images-playbook.yml \
#           --extra-vars="registry=aws_account_id.dkr.ecr.region.amazonaws.com/"
#

- hosts: "localhost"
  connection: "local"

  vars:

    projects:

      # Need to check this out to a separate folder to force images to be built
      # after main images playbook has been executed
      - name: "RDSS Archivematica Channel Adapter"
        repo: "https://github.com/JiscRDSS/rdss-archivematica-channel-adapter"
        version: "v0.6.0"
        dest: "./src/qa/rdss-archivematica-channel-adapter"
        images:
          - name: "{{ registry }}dynalite"
            path: "./src/qa/rdss-archivematica-channel-adapter/hack/minikine"
            dockerfile: "dynalite.Dockerfile"
          - name: "{{ registry }}minikine"
            path: "./src/qa/rdss-archivematica-channel-adapter/hack/minikine"
            dockerfile: "minikine.Dockerfile"

      - name: "RDSS Archivematica MsgCreator"
        repo: "https://github.com/JiscRDSS/rdss-archivematica-msgcreator"
        version: "v0.1.0"
        dest: "./src/qa/rdss-archivematica-msgcreator"
        images:
          - name: "{{ registry }}rdss-archivematica-msgcreator"
            dockerfile: "Dockerfile"
            path: "./src/qa/rdss-archivematica-msgcreator/"

  tasks:

    - name: "Ensure that the variable registry is defined"
      fail:
        msg: "Variable registry is undefined or empty"
      when: "(registry is not defined) or (registry | trim == '')"

    - name: "Install playbook dependencies"
      pip:
        name: "{{ item }}"
        extra_args: "--user"
      with_items:
        - "setuptools"
        - "docker"

    - name: "Clone repositories"
      git:
        accept_hostkey: "yes"
        repo: "{{ item.repo }}"
        dest: "{{ item.dest }}"
        version: "{{ item.version }}"
      register: "git_clone"
      with_items: "{{ projects }}"
      tags:
        - "clone"

    - name: "Build and tag images"
      command: "docker build
        -t {{ item.1.name }}:{{ item.0.item.version | regex_replace('/', '_')  | truncate(128, True)}}
        -t {{ item.1.name }}:latest
        --build-arg ARCHIVEMATICA_VERSION={{ rdss_version }}
        --build-arg AGENT_CODE={{ rdss_version }}
        -f {{ item.1.dockerfile }} ."
      args:
        chdir: "{{ item.1.path }}"
      when: item.0.changed
      with_subelements:
        - "{{ git_clone.results }}"
        - item.images
      tags:
        - "build"
        # Ignore false ANSIBLE0016 claiming this task should be a handler
        - skip_ansible_lint

    - name: "Publish images"
      command: docker push "{{ item.1.name }}"
      when: item.0.changed
      with_subelements:
        - "{{ git_clone.results }}"
        - item.images
      tags:
        - "publish"
        # Ignore false ANSIBLE0016 claiming this task should be a handler
        - skip_ansible_lint
